---
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/dokku@master
        with:
          # specify the `develop` branch as the remote branch to push to
          branch: 'develop'
          git_remote_url: 'ssh://dokku@dokku.myhost.ca:22/appname'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
