---
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dokku.me:22/appname'
          # specify an alternative ssh host key
          ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
